### ISSUE TITLE
ES6 modules and estree compatibility

### ISSUE THREAD

**Issue by tobich** [benjamn/ast-types#111]
@benjamn Following the esprima-fb's [planned deprecation](https://github.com/facebook/esprima/issues/111), I've put together forks of ast-types and recast which work with babel-core/acorn as parser instead. The biggest issue seems to be the incompatibility of Export and Import specifiers in esprima-fb vs estree/acorn/everybody else. As far as I understand, both definition sets cannot be included at the same time (several type names overlap). In case you are interested in pull request – what approach do you suggest? Abandoning esprima-fb altogether, or some kind of configuration/multiple main.js/other?

**Comment by amasad** [comment]
:+1:

**Comment by benjamn** [comment]
Please go ahead and submit a pull request for the babel-core/acorn version of the AST, and we'll figure out a way to let users choose which version to use (see #57). For clarity, you might be able to put the modified definitions in their own file, so that they just override the old definitions when the new file is evaluated.

Thanks a ton @tobich!

**Comment by tobich** [comment]
I am trying to get the [pull request](https://github.com/benjamn/ast-types/pull/112) through, but [the CI seems to be using really ancient node/npm](https://travis-ci.org/benjamn/ast-types/jobs/60668304), it cannot install babel-core. :-(

**Comment by benjamn** [comment]
Fixed by https://github.com/benjamn/ast-types/commit/0f3f363c8d6347d393c4509fee41c22e514dda0e, hopefully!
