### ISSUE TITLE
`.visit(...)` does not visit nodes that do not extend Printable 

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/ast-types#123]
This may make sense / not matter for processing ECMAScript related AST's, but it is a weird requirement to force on implementors of custom AST's.

This is a blocker for #57

**Comment by jamestalmage** [comment]
It appears this was intentional in @843b55b.

I have not yet figured out why visiting non-Printable nodes would be a bad idea, even in the ECMAScript context.

Assuming there are good reasons for it, perhaps we generalize `path-visitor` to take a custom filter function. The default would be to allow everything, but `types.visit` would expose an instance that filtered out non-Printable nodes.

Also (or possibly alternatively), it might be good to extend field definitions (i.e. `def(...).field(...)`) with a `visitable` flag, and make a `types.getVisitableFields`, or just pass a `getVisitableFields` implementation to the generalized `path-visitor`.

**Comment by benjamn** [comment]
I'm also having trouble remembering the original rationale… I think it was just for performance reasons (not visiting `.loc`, mostly), but that can be avoided in other ways.

**Comment by jamestalmage** [comment]
I think that `Printable.check(...)` line may also be what prevents it from trying to visit fields with primitive values.

**Comment by benjamn** [comment]
Digging deeper into the background, visitation used to be restricted to subtypes of `Node`, which is more restrictive than `Printable`. I switched to `Printable` in [this commit](https://github.com/benjamn/ast-types/commit/d35fd6e94080b0d88a658703fbbccb7ca1be805c) in order to allow visiting non-`Node` printable things like comments (but still forbid things like `SourceLocation`s).

I'm persuaded by your argument that we should relax the restriction even further. In order to be visitable, I think an object just needs to have a string-valued `.type` field, since that's what we look up in `this._methodNameTable` anyway.
