### ISSUE TITLE
Support for new babel types

### ISSUE THREAD

**Issue by tmcw** [benjamn/ast-types#132]
Re: https://github.com/babel/babel/issues/2769

Babel 6.0.0 introduces a new NumericLiteral type that currently is not present in ast-types and breaks the tree traversal.

**Comment by benjamn** [comment]
Have time to submit a pull request?

**Comment by hzoo** [comment]
It's more than just `NumericLiteral` - https://github.com/babel/babel/blob/master/doc/ast/spec.md, https://github.com/babel/babel/blob/master/CHANGELOG.md#600

Example changes - https://github.com/babel/acorn-to-esprima/pull/3/files#diff-d45f2be38f06b237a94ba1f97798af79R53

**Comment by benjamn** [comment]
I'm guessing @tmcw doesn't have time for a pull request, which is totally fine. I'll do this as soon as I can.

**Comment by hzoo** [comment]
Shouldn't be too bad. From the changelog

Rename RegexLiteral node to RegExpLiteral.
Rename NumberLiteral node to NumericLiteral.

The MethodDefinition node type has been renamed to ClassMethod and it's FunctionExpression value property has been coerced into the main method node.
The Property node type has been renamed to ObjectProperty.
The Property node type with the boolean flag method has been renamed to ObjectMethod and it's FunctionExpression value property has been coerced into the main method node.
The Literal node type has been unoverloaded and split into BooleanLiteral, RegExpLiteral, NumericLiteral, StringLiteral and NullLiteral.
The SpreadProperty (from object-rest-spread) node type has been split into RestProperty (for ObjectPattern) and SpreadProperty (for ObjectExpression)

**Comment by benjamn** [comment]
Those are all really worthwhile changes, by the way.

**Comment by hzoo** [comment]
Should probably propose them to ESTree anyway (lgtm)

**Comment by jamestalmage** [comment]
I think this is going to be difficult w/o #57.

For example: attempting to add RegExpLiteral [per the spec](https://github.com/babel/babel/blob/master/doc/ast/spec.md#literals), I added the following definition:

```js
def("RegExpLiteral")
    .bases("Literal")
    .build("pattern", "flags")
    .field("pattern", String)
    .field("flags", String);
```

Trying to build a `RegExpLiteral` Node, you get the following error:

```js
b.regExpLiteral("my-pattern", "ig");
```
```
 Error: no value or default function given for field "value" of RegExpLiteral("pattern": string, "flags": string)
```

This is because `core.js` defines a required `value` field for `Literal`, where the Babel spec uses `Literal` strictly as a super-type for the more specific nodes (StringLiteral, NullLiteral, etc).

Until `ast-types` is refactored to allow custom Node definitions, these increasingly divergent AST specs are going to represent a problem.

**Comment by hzoo** [comment]
Update: I made https://github.com/benjamn/ast-types/pull/162
