### ISSUE TITLE
Generate a browser-friendly .js file containing all dependencies

### ISSUE THREAD

**Issue by benjamn** [benjamn/ast-types#6]
Executing the file in a browser should define a global variable called `AstTypes`.

This will require shimming `Object.defineProperty`, among other things.

**Comment by balumuriraj** [comment]
any update on this one? or is there any work around to get this work on a browser?

**Comment by zertosh** [comment]
@benjamn ast-types builds perfectly fine with browserify. The only problem is that the `assert` module is kinda big (22% of the lines in the built bundle). Since only `assert.ok` and `assert.strictEqual` are used, it would be trivial to replace them with simple ifs and throws. If this is something you'd accept, I'd be more than happy to submit a PR.

I'm assuming that shimming `Object.defineProperty` was a 2013 concern that is no longer so in 2015.

**Comment by zertosh** [comment]
FWIW, babel depends on ast-types and it ships a browser version of itself [bundled with browserify](https://github.com/babel/babel/blob/v5.8.19/packages/babel/scripts/build-dist.sh). So ast-types is browser-friendly already, but it would be nice to remove the `assert` module bloat.

**Comment by thejameskyle** [comment]
ping

**Comment by zertosh** [comment]
Hmm issues referenced in titles aren't linked back. Oh well. See https://github.com/benjamn/ast-types/pull/128

**Comment by benjamn** [comment]
see also https://github.com/babel/babel/pull/2424
