### ISSUE TITLE
A way to break visitor

### ISSUE THREAD

**Issue by dfcreative** [benjamn/ast-types#89]
Is there a way to break traversing?
For example, it can be done via throwing an exception:
```js
var visitor = {};
visitor['visit' + nodeType] = function (path) {
	this.traverse(path);
	if (!test(path.node)) throw 1;
};
try {
 visit(ast, visitor);
} catch (e) {}
```

But is there a more elegant way to do so?
Like `this.break()`, or `this.stop()` within the callback, similar to `this.traverse(path)`?

**Comment by fkling** [comment]
Do you mean `return false;` (and not calling `this.traverse`), which would not descent further at that node? Or do you want to completely stop traversing the AST?

**Comment by dfcreative** [comment]
Yes, i mean to completely stop traversing

**Comment by benjamn** [comment]
Yep, throwing an exception is currently the best way to abort not just the current subtree (`return false` for that) but all remaining nodes. I like the semantics of throwing an exception, because you could potentially catch it in an ancestor visitor if you wanted to.

I'm curious if your hesitance to use exceptions has more to do with performance, or the burden of writing your own `try`-`catch` block to intercept the exception. If the latter, I'd be happy to consider a special exception type that could be caught in the top-level `PathVisitor.prototype.visit` method.

**Comment by benjamn** [comment]
Published support for `PathVisitor.prototype.abort` just now (v0.6.13): https://www.npmjs.com/package/ast-types.

Thanks for the idea!

**Comment by dfcreative** [comment]
Wow, that's great! Thank you a lot, that really simplifies things in two upcoming projects - ast-test and ast-replace.

**Comment by benjamn** [comment]
Nice, I'm glad to hear it, and looking forward to seeing what you do with those projects :)

**Comment by dfcreative** [comment]
Yes, here they are: [ast-replace](https://github.com/dfcreative/ast-replace), [ast-test](https://github.com/dfcreative/ast-test).
