### ISSUE TITLE
Traversing comment nodes.

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/ast-types#90]
Is that doable via:
```javascript
{
  visitBlock:....
}
```
[this](https://github.com/benjamn/ast-types/blob/master/def/core.js#L364) makes me think no

**Comment by benjamn** [comment]
Ah, the problem is that `.comments` is a "hidden" field of the `Node` type, due to the `true` argument here:
```js
def("Node")
    .bases("Printable")
    .field("type", isString)
    .field("comments", or(
        [def("Comment")],
        null
    ), defaults["null"], true);
```
I'm tempted to un-hide it, because I doubt anything would break. In order for code that previously used `types.visit` to be broken by this change, the visitor would have to have a `visitPrintable` method and also not be prepared to handle comments, which seems unlikely.

**Comment by benjamn** [comment]
On the other hand, maybe a safer approach would be to modify the visitor code so that it visits `.comments` if present, in addition to the fields given by `types.getFieldNames`.

**Comment by jamestalmage** [comment]
Wow, thank you!
Blown away by this api man.  Seriously great.
